# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list',
            new_name='list1',
        ),
    ]
