# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-14 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20190614_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='list1',
            new_name='list',
        ),
    ]
